- name: App setup
  include_role:
    name: common
    tasks_from: app-setup

- name: Maven setup
  include_role:
    name: common
    tasks_from: maven-setup

- name: Copy DB files to MySQL server
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/tmp/"
    remote_src: yes
  loop:
    - files/schema.sql
    - files/app-user.sql
    - files/master-data.sql
  delegate_to: "{{ MYSQL_HOST }}"

- name: Import DB files
  community.mysql.mysql_db:
    name: all
    state: import
    target: "/tmp/{{ item }}"
    login_user: "{{ MYSQL_ROOT_USER }}"
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    login_host: "{{ MYSQL_HOST }}"
  loop:
    - schema.sql
    - app-user.sql
    - master-data.sql
  delegate_to: "{{ MYSQL_HOST }}"

- name: Systemd setup
  include_role:
    name: common
    tasks_from: systemd
