- name: App setup
  include_role:
    name: common
    tasks_from: app-setup

- name: Maven setup
  include_role:
    name: common
    tasks_from: maven-setup

- name: Import SQL files from shipping to MySQL server
  ansible.builtin.shell: >
    mysql -h {{ MYSQL_HOST }} -u{{ MYSQL_ROOT_USER }} -p{{ MYSQL_ROOT_PASSWORD }} < {{ item }}
  args:
    chdir: /app/db
  loop:
    - schema.sql
    - app-user.sql
    - master-data.sql
  tags: [one_time_sql]

- name: Systemd setup
  include_role:
    name: common
    tasks_from: systemd
