- name: App setup
  include_role:
    name: common
    tasks_from: app-setup

- name: Maven setup
  include_role:
    name: common
    tasks_from: maven

- name: Copy DB files from shipping to mysql
  ansible.builtin.fetch:
    src: /app/db/{{ item }}
    dest: /tmp/
    flat: yes
  loop:
    - schema.sql
    - app-user.sql
    - master-data.sql
  delegate_to: shipping.deeps.sbs

- name: Import DB into MySQL
  community.mysql.mysql_db:
    name: all
    state: import
    login_user: "{{ MYSQL_ROOT_USER }}"
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    login_host: "{{ MYSQL_HOST }}"
    target: "/tmp/{{ item }}"
  loop:
    - schema.sql
    - app-user.sql
    - master-data.sql
  delegate_to: mysql.deeps.sbs

- name: Systemd setup
  include_role:
    name: common
    tasks_from: systemd.yaml
