- name: App setup
  include_role:
    name: common
    tasks_from: app-setup

- name: Maven setup
  include_role:
    name: common
    tasks_from: maven-setup

- name: Import DB SQL files
  ansible.builtin.command: >
    mysql -h {{ MYSQL_HOST }} -u{{ MYSQL_ROOT_USER }} -p{{ MYSQL_ROOT_PASSWORD }} < /tmp/{{ item }}
  loop:
    - schema.sql
    - app-user.sql
    - master-data.sql
  delegate_to: "{{ MYSQL_HOST }}"

- name: Systemd setup
  include_role:
    name: common
    tasks_from: systemd
