- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: python3-pip setup
  include_role:
    name: common
    tasks_from: python-setup

- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd.yaml
