- name: Install dependencies
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - gcc
    - python3-devel
    - python3-pip

- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: Install pip requirements
  ansible.builtin.pip:
    requirements: requirements.txt
    executable: pip3
  args:
    chdir: /app

- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd.yaml
