- name: Installing mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Install PyMySQL for Ansible MySQL modules
  ansible.builtin.pip:
    name: PyMySQL
    executable: pip3

- name: Starting and enabling mysql service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Set MySQL root password (first-time setup)
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "RoboShop@1"
    login_unix_socket: /var/lib/mysql/mysql.sock
    check_implicit_admin: true
    state: present
