- name: Install dependencies
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - gcc
    - python3-devel
    - python3-pip

- name: Install dependencies
  ansible.builtin.pip:
    requirements: requirements.txt
    executable: pip3
  args:
    chdir: /app
