  - name: copy catalogue service to system directory
    ansible.builtin.template:
      src: catalogue.service.j2
      dest: /etc/systemd/system/catalogue.service
  
  - name: systemctl daemon-reload
    ansible.builtin.systemd_service:
      daemon_reload: yes
  
  - name: Enable and start catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes